name: FullWorkflow-Deploy-b

on:
  push:
    branches:
      - main
    paths:
      - 'model/b/**'
  pull_request:
    branches:
      - main
    paths:
      - 'model/b/**'

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  tests_b:
    uses: ./.github/workflows/tests.yml
    with:
      src_path: "model/b"
  release:
    needs: [tests_b]
    uses: ./.github/workflows/release.yaml
