name: FullWorkflow-Deploy-a

on:
  push:
    branches:
      - main
    paths:
      - 'model/a/**'
  pull-request:
    branches:
      - main
    paths:
      - 'model/a/**'

permissions:
  contents: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  tests_a:
    uses: ./.github/workflows/tests.yml
    with:
      src_path: "model/a"
  release:
    needs: [tests_a]
    uses: ./.github/workflows/release.yaml
